#include "positions.h"
void danss_draw_report(const char *fname, double bgScale = 2.24)
{
	char pname[1024];
	int i;
	int N;
	TCanvas *cv;
	TFile *f;
	TH1 *h;
	TH1 *hb;
	TH1 *h1;
	TH1 *hb1;
	char str[1024];
	TVirtualPad *pd;
	TLatex *txt;
	double val, err;
	char *ptr;
	TPad *subPad;
	
	gStyle->SetOptStat(0);
	strncpy(pname, fname, sizeof(pname) - 5);
	ptr = strstr(pname, ".root");
	if (ptr) *ptr = '\0';
	strcat(pname, ".pdf");
	N = sizeof(positions) / sizeof(positions[0]);
	cv = new TCanvas("CV", "Results", 1600, 800);
	f = new TFile(fname);
	if (!f->IsOpen()) return;
	sprintf(str, "%s[", pname);
	cv->Print(str);
	txt = new TLatex();
	txt->SetTextSize(0.05);
//	subPad = new TPad("subPad", "", 0.75, 0.5, 0.9, 0.7);
	
	for (i=0; i<N; i++) {
		cv->Clear();
		cv->cd(0)->SetFillStyle(4000);
		cv->Divide(2, 1);
		cv->cd(0)->SetFillStyle(4000);
		pd = cv->cd(1);
		pd->Divide(1, 2);
		pd->cd(1);

		sprintf(str, "%s_hSig-sig", positions[i].name);
		h = (TH1 *) f->Get(str);
		if (!h) {
			printf("%s not found in %s\n", positions[i].name, fname);
			continue;
		}
		h->SetLineWidth(2);
		h->SetLineColor(kBlue);
		h->SetTitle("Neutrino events after veto");
		h->Draw();
		val = h->IntegralAndError(1, h->FindBin(7.999), err);
		sprintf(str, "Signal = %5.0f+-%4.0f", val, err);
		txt->SetTextColor(kBlue);
		txt->DrawTextNDC(0.4, 0.8, str);
		sprintf(str, "%s_hSig-rand", positions[i].name);
		h = (TH1 *) f->Get(str);
		if (!h) continue;
		h->SetLineWidth(2);
		h->SetLineColor(kBlack);
		h->Draw("same");
		val = h->IntegralAndError(1, h->FindBin(7.999), err);
		sprintf(str, "Random = %5.0f+-%4.0f", val, err);
		txt->SetTextColor(kBlack);
		txt->DrawTextNDC(0.4, 0.7, str);
		sprintf(str, "%s_hSig-diff", positions[i].name);
		h = (TH1 *) f->Get(str);
		if (!h) continue;
		h->SetLineWidth(2);
		h->SetLineColor(kRed);
		h->Draw("same");
		val = h->IntegralAndError(1, h->FindBin(7.999), err);
		sprintf(str, "Result = %5.0f+-%4.0f", val, err);
		txt->SetTextColor(kRed);
		txt->DrawTextNDC(0.4, 0.6, str);
		
		pd->cd(2);
		sprintf(str, "%s_hCosm-sig", positions[i].name);
		h = (TH1 *) f->Get(str);
		if (!h) continue;
		h->SetLineWidth(2);
		h->SetLineColor(kBlue);
		h->SetTitle("Cosmic background");
		h->Draw();
		val = h->IntegralAndError(1, h->FindBin(7.999), err);
		sprintf(str, "Signal = %5.0f+-%4.0f", val, err);
		txt->SetTextColor(kBlue);
		txt->DrawTextNDC(0.4, 0.8, str);
		sprintf(str, "%s_hCosm-rand", positions[i].name);
		h = (TH1 *) f->Get(str);
		if (!h) continue;
		h->SetLineWidth(2);
		h->SetLineColor(kBlack);
		h->Draw("same");
		val = h->IntegralAndError(1, h->FindBin(7.999), err);
		sprintf(str, "Random = %5.0f+-%4.0f", val, err);
		txt->SetTextColor(kBlack);
		txt->DrawTextNDC(0.4, 0.73, str);
		sprintf(str, "%s_hCosm-murand", positions[i].name);
		hb = (TH1 *) f->Get(str);
		if (!hb) continue;
		hb->SetLineWidth(2);
		hb->SetLineColor(kMagenta);
		hb->Draw("same");
		val = hb->IntegralAndError(1, hb->FindBin(7.999), err);
		sprintf(str, "MuRandom = %5.0f+-%4.0f", val, err);
		txt->SetTextColor(kMagenta);
		txt->DrawTextNDC(0.4, 0.66, str);
		sprintf(str, "%s_hCosm-diff", positions[i].name);
		h = (TH1 *) f->Get(str);
		if (!h) continue;
		h->Add(hb, -1);
		h->SetLineWidth(2);
		h->SetLineColor(kRed);
		h->Draw("same");
		val = h->IntegralAndError(1, h->FindBin(7.999), err);
		sprintf(str, "Result = %5.0f+-%4.0f", val, err);
		txt->SetTextColor(kRed);
		txt->DrawTextNDC(0.4, 0.59, str);
		
		pd = cv->cd(2);
		pd->SetFillStyle(4000);
		sprintf(str, "%s_hSig", positions[i].name);
		h = (TH1 *) f->Get(str);
		if (!h) continue;
//		sprintf(str, "%s_hRes", positions[i].name);
//		h = (TH1 *) f->Get(str);
//		if (!h) continue;
		h->SetLineWidth(2);
		h->SetLineColor(kRed);
		sprintf(str, "%s (%d - %d)", positions[i].name, positions[i].first, positions[i].last);
		h->SetTitle(str);
		sprintf(str, "%s_hCosm", positions[i].name);
		hb = (TH1 *) f->Get(str);
		if (!hb) continue;
		hb->SetLineWidth(2);
		hb->SetLineColor(kBlue);
		hb->SetFillStyle(kSolid);
		hb->SetFillColor(kBlue);
		hb->Scale(positions[i].bgnd * bgScale);
		h->Add(hb, -1.0);
		h->Draw();
		val = h->IntegralAndError(1, h->FindBin(7.999), err);
		sprintf(str, "Neutrino = %5.2f+-%4.2f mHz", val, err);
		txt->SetTextColor(kRed);
		txt->DrawTextNDC(0.3, 0.85, str);
		hb->Draw("same");
		val = hb->IntegralAndError(1, h->FindBin(7.999), err);
		sprintf(str, "Cosm = %5.2f+-%4.2f mHz (%4.1f%%)", val, err, 100*positions[i].bgnd * bgScale);
		txt->SetTextColor(kBlue);
		txt->DrawTextNDC(0.3, 0.8, str);
		sprintf(str, "%s_hConst", positions[i].name);
		val = ((TH1D*)f->Get(str))->GetBinContent(1);
		sprintf(str, "Time = %6.1f*10^3 s", val / 1000.0);
		txt->SetTextColor(kBlack);
		txt->DrawTextNDC(0.3, 0.75, str);

//		subPad = new TPad("subPad", "", 0.5, 0.5, 0.8, 0.7);
//		subPad->cd();
		cv->Update();
		cv->Print(pname);
		cv->Clear();
		
		sprintf(str, "%s_1", h->GetName());
		h1 = (TH1*) h->Clone(str);
		sprintf(str, "%s_1", hb->GetName());
		hb1 = (TH1 *) hb->Clone(str);
		if (h1->GetMinimum() > 0) h1->SetMinimum(0);
		h1->GetXaxis()->SetRange(h1->FindBin(7.001), h1->GetNbinsX());
		h1->Draw();
		val = h->IntegralAndError(h->FindBin(9.001), h->FindBin(11.999), err);
		sprintf(str, "[9-12] MeV = %5.2f+-%4.2f mHz", val, err);
		txt->SetTextColor(kRed);
		txt->DrawTextNDC(0.3, 0.85, str);
		hb1->Draw("same");
		val = hb->IntegralAndError(hb->FindBin(9.001), hb->FindBin(11.999), err);
		sprintf(str, "[9-12] MeV = %5.2f+-%4.2f mHz (%4.1f%%)", val, err, 100*positions[i].bgnd * bgScale);
		txt->SetTextColor(kBlue);
		txt->DrawTextNDC(0.3, 0.8, str);
		
		cv->Update();
		cv->Print(pname);
	}
	sprintf(str, "%s]", pname);
	cv->Print(str);
	f->Close();
	delete cv;
}
